In [1]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

#Task 1

In [12]:
print(np.shape(data))
mean_per_station = data.mean(axis=1)
for i, mean in enumerate(mean_per_station):
    print(f"Station {i+1} mean temperature: {mean:.2f}")

(4, 5)
Station 1 mean temperature: 25.30
Station 2 mean temperature: 23.78
Station 3 mean temperature: 26.58
Station 4 mean temperature: 25.26


#Task 2


In [14]:
mask = data > 28.0
print(f"Boolean mask:\n{mask}")

above_28 = data[mask]
print(f"\n1D array of readings above 28.0:\n{above_28}")

Boolean mask:
[[False False  True  True False]
 [False False  True False False]
 [ True  True False False False]
 [False False  True  True False]]

1D array of readings above 28.0:
[31.2 28.7 30.5 33.1 29.6 31.9 28.1]


#Task 3

In [15]:
normalized = (data - data.min()) / (data.max() - data.min())
print(f"Normalized array (rounded to 2 decimal places):\n{np.round(normalized, 2)}")

Normalized array (rounded to 2 decimal places):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
